drop table library.books CASCADE;
drop table library.articles CASCADE;
drop table library.genres CASCADE;
drop table library.persons CASCADE;
drop table library.readers CASCADE;
drop table library.authors CASCADE;
drop table library.book_instances CASCADE;
drop table library.issue_return_books CASCADE;
drop table library.books_articles CASCADE;
drop table library.articles_genres CASCADE;
drop table library.authors_articles CASCADE;
drop FUNCTION library.get_books_by_author;
drop FUNCTION library.get_books_by_article;
drop FUNCTION library.get_articles_by_author;
drop procedure library.issue_and_return_books;
drop procedure if exists library.delete_person;
drop procedure if exists library.insert_book;
drop procedure if exists library.update_person;
drop procedure if exists library.insert_person;
drop procedure if exists library.delete_book;
drop procedure if exists library.update_book;
